#!/bin/bash

NAMESPACE="kube-system"
RESOURCE="pods"

echo "Resource, Namespace, Name, CPU, Memory"

kubectl top $RESOURCE -n $NAMESPACE | tail -n +2 | while read -r line; do
  read -r NAME CPU MEMORY <<< "$line"
  echo "$RESOURCE, $NAMESPACE, $NAME, $CPU, $MEMORY"
done
