apiVersion: batch/v1
kind: Job
metadata:
  name: app-job
spec:
  template:
    spec:
      containers:
        - name: app
          image: busybox
          command: ["echo", "Hello Job"]
      restartPolicy: Never