apiVersion: v1
kind: Pod
metadata:
  name: app-liveness
spec:
  containers:
    - name: app
      image: nginx
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10