apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  containers:
    - name: app
      image: nginx
      env:
        - name: SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: token