apiVersion: v1
kind: Pod
metadata:
  name: app-readiness
spec:
  containers:
    - name: app
      image: nginx
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
