apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: app
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes CronJob
          restartPolicy: OnFailure